# Generated by Django 6.0.2 on 2026-03-31 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_department_alter_profile_role_alter_staff_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='institution',
            name='admin_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='institution',
            name='admin_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='institution',
            name='allow_online_payment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='institution',
            name='currency',
            field=models.CharField(default='NGN', max_length=10),
        ),
        migrations.AddField(
            model_name='institution',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='institution',
            name='favicon',
            field=models.FileField(blank=True, null=True, upload_to='institutions/favicons/'),
        ),
        migrations.AddField(
            model_name='institution',
            name='grading_system',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('gpa', 'GPA'), ('custom', 'Custom')], default='percentage', max_length=20),
        ),
        migrations.AddField(
            model_name='institution',
            name='has_departments',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='institution',
            name='has_faculties',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='institution',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='institutions/logos/'),
        ),
        migrations.AddField(
            model_name='institution',
            name='max_grade',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=5),
        ),
        migrations.AddField(
            model_name='institution',
            name='ownership_type',
            field=models.CharField(choices=[('private', 'Private'), ('public', 'Public'), ('government', 'Government')], default='private', max_length=20),
        ),
        migrations.AddField(
            model_name='institution',
            name='payment_provider',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='institution',
            name='payment_public_key',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='institution',
            name='payment_secret_key',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='institution',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='institution',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='institution',
            name='short_name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='institution',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='institution',
            name='theme_color',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='institution',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='year_established',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='country',
            field=models.CharField(default='Nigeria', max_length=100),
        ),
    ]
