# Generated by Django 6.0.2 on 2026-03-31 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_institution_address_institution_admin_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='cac_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='institution',
            name='license_number',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
