# Generated by Django 6.0.2 on 2026-03-31 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_profile_approved_at_profile_approved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='school_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
