# Generated by Django 6.0.2 on 2026-04-01 07:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_institution_user_sequence'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('academic_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.academicclass')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='core.institution')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.staff')),
            ],
        ),
        migrations.AddField(
            model_name='staff',
            name='classes',
            field=models.ManyToManyField(blank=True, through='core.TeacherAssignment', to='core.academicclass'),
        ),
    ]
