# Generated by Django 6.0.2 on 2026-04-01 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_teacherassignment_staff_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='staff/photos/'),
        ),
        migrations.AddField(
            model_name='student',
            name='next_of_kin_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='student',
            name='next_of_kin_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='student',
            name='next_of_kin_relationship',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='students/photos/'),
        ),
    ]
