# Generated by Django 6.0.2 on 2026-04-01 09:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_fee_applies_to_all_fee_classes_fee_departments_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(blank=True, max_length=20)),
                ('term', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('reviewed', 'Reviewed'), ('approved', 'Approved')], default='submitted', max_length=20)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('academic_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.academicclass')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_submissions', to='core.institution')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subject')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_submissions', to='core.staff')),
            ],
        ),
    ]
