# Generated by Codex on 2026-08-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_teachersubjectassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='billing_period',
            field=models.CharField(choices=[('term', 'Per Term'), ('session', 'Per Session')], default='term', max_length=20),
        ),
        migrations.AddField(
            model_name='institution',
            name='selected_package',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
