# Generated by Django 6.0.2 on 2026-02-20 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='monthly_fee',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='subscription_active_until',
            field=models.DateField(blank=True, null=True),
        ),
    ]
