# Generated by Django 6.0.2 on 2026-02-21 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_monthly_fee_user_subscription_active_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_code_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verification_code',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
