# Generated by Django 6.0.2 on 2026-03-23 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_vat_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('code', ''), _negated=True), fields=('user', 'code'), name='unique_product_code_per_user'),
        ),
    ]
