# Generated by Django 6.0.2 on 2026-04-02 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_decimal_quantity_and_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='monthly_fee',
            field=models.DecimalField(decimal_places=2, default=2000, max_digits=10),
        ),
    ]
