# Generated by Django 6.0.2 on 2026-04-17 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_delivery_rider_company_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplacebuyer',
            name='is_phone_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='marketplacebuyer',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='marketplacebuyer',
            name='phone_code_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marketplacebuyer',
            name='phone_verification_code',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='marketplacebuyer',
            name='registration_role',
            field=models.CharField(choices=[('customer', 'Customer'), ('rider', 'Rider')], default='customer', max_length=20),
        ),
    ]
