# Generated by Django 6.0.2 on 2026-04-20 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_user_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverycompany',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='deliveryrequest',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='deliveryrider',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
