# Generated by Django 6.0.2 on 2026-04-21 04:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_alter_deliverycompany_id_alter_deliveryrequest_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('access_token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('buyer_name', models.CharField(max_length=255)),
                ('buyer_contact', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='house_inquiries', to='core.marketplacebuyer')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='core.houselisting')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='house_inquiries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HouseInquiryMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(choices=[('buyer', 'Buyer'), ('seller', 'Seller'), ('system', 'System')], default='buyer', max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.houseinquiry')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
