# Generated by Django 6.0.2 on 2026-05-09 02:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_multibranch_shop_management'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bank_account_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='user',
            name='bank_account_number',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='bank_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sales_channel',
            field=models.CharField(choices=[('owner_pos', 'Owner POS'), ('marketplace', 'Marketplace'), ('shopboy_portal', 'Shop Boy Portal'), ('customer_scan', 'Customer Scanner')], default='owner_pos', max_length=30),
        ),
        migrations.CreateModel(
            name='CustomerScanCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_token', models.CharField(default=uuid.uuid4, max_length=80, unique=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('customer_name', models.CharField(blank=True, max_length=150)),
                ('customer_phone', models.CharField(blank=True, max_length=30)),
                ('is_checked_out', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_scan_carts', to='core.shopbranch')),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_carts', to='core.marketplacebuyer')),
                ('pending_sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_cart', to='core.sale')),
                ('shop_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_scan_carts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
