# Generated by Django 6.0.2 on 2026-05-15 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_user_bank_account_name_user_bank_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allow_staff_offline_sales',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='offline_staff_max_pending_sales',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='user',
            name='offline_staff_max_sale_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='offline_staff_pin',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
        migrations.AddField(
            model_name='user',
            name='offline_sync_warning_hours',
            field=models.PositiveIntegerField(default=24),
        ),
    ]
