# Generated by Django 6.0.2 on 2026-05-15 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_user_allow_staff_offline_sales_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='monthly_fee',
            field=models.DecimalField(decimal_places=2, default=4000, max_digits=10),
        ),
    ]
