# Generated by Django 6.0.2 on 2026-05-15 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_alter_user_monthly_fee'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAssistantMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_assistant_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIReceiptScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='ai_receipts/')),
                ('raw_text', models.TextField(blank=True)),
                ('parsed_items', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('parsed', 'Parsed'), ('applied', 'Applied to inventory'), ('needs_review', 'Needs review')], default='needs_review', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by_shopboy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_receipt_scans', to='core.shopboy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_receipt_scans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
