from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .import views
from . import api


urlpatterns = [
    path('api/marketplace/auth/signup/', api.api_marketplace_signup, name='api_marketplace_signup'),
    path('api/marketplace/auth/login/', api.api_marketplace_login, name='api_marketplace_login'),
    path('api/marketplace/auth/verify/', api.api_marketplace_verify, name='api_marketplace_verify'),
    path('api/marketplace/auth/resend-code/', api.api_marketplace_resend_code, name='api_marketplace_resend_code'),
    path('api/marketplace/auth/forgot-password/request/', api.api_marketplace_forgot_password_request, name='api_marketplace_forgot_password_request'),
    path('api/marketplace/auth/forgot-password/verify/', api.api_marketplace_forgot_password_verify, name='api_marketplace_forgot_password_verify'),
    path('api/marketplace/auth/forgot-password/reset/', api.api_marketplace_forgot_password_reset, name='api_marketplace_forgot_password_reset'),
    path('api/marketplace/auth/logout/', api.api_marketplace_logout, name='api_marketplace_logout'),
    path('api/marketplace/me/', api.api_marketplace_me, name='api_marketplace_me'),
    path('api/marketplace/shops/', api.api_marketplace_shops, name='api_marketplace_shops'),
    path('api/marketplace/shops/<str:username>/', api.api_marketplace_shop_detail, name='api_marketplace_shop_detail'),
    path('api/marketplace/shops/<str:username>/orders/', api.api_marketplace_place_order, name='api_marketplace_place_order'),
    path('api/marketplace/orders/', api.api_marketplace_orders, name='api_marketplace_orders'),
    path('api/marketplace/orders/<uuid:public_id>/', api.api_marketplace_order_detail, name='api_marketplace_order_detail'),
    path('api/marketplace/orders/<uuid:public_id>/messages/', api.api_marketplace_order_message, name='api_marketplace_order_message'),
    path('add_category', views.add_category, name='add_category'),
    path('add_product', views.add_product, name='add_product'),
    path('adjust-stock/<int:pk>/', views.adjust_stock, name='adjust_stock'),
    path('edit-product/<int:pk>/', views.edit_product, name='edit_product'),
    path('delete-product/<int:pk>/', views.delete_product, name='delete_product'),
    path('login/', views.login_view, name='login'),
    path('subscription/payment/', views.subscription_payment, name='subscription_payment'),
    path('forgot-password/', views.forgot_password, name='forgot_password'),
    path('forgot-password/send-code/', views.forgot_password_send_code, name='forgot_password_send_code'),
    path('forgot-password/verify/', views.forgot_password_verify_code, name='forgot_password_verify_code'),
    path('forgot-password/reset/', views.forgot_password_reset, name='forgot_password_reset'),
    path('shopboy/login/', views.shopboy_login, name='shopboy_login'),
    path('shopboy/dashboard/', views.shopboy_dashboard, name='shopboy_dashboard'),
    path('shopboy/sell/<int:product_id>/', views.shopboy_sell_product, name='shopboy_sell_product'),
    path('shopboy/cart/add/<int:product_id>/', views.shopboy_add_to_cart, name='shopboy_add_to_cart'),
    path('shopboy/cart/update/<int:product_id>/', views.shopboy_update_cart, name='shopboy_update_cart'),
    path('shopboy/cart/remove/<int:product_id>/', views.shopboy_remove_from_cart, name='shopboy_remove_from_cart'),
    path('shopboy/cart/checkout/', views.shopboy_checkout, name='shopboy_checkout'),
    path('shopboy/logout/', views.shopboy_logout, name='shopboy_logout'),
    path('shopboy/profile/', views.shopboy_profile, name='shopboy_profile'),
    path('admin-portal/login/', views.admin_portal_login, name='admin_portal_login'),
    path('admin-portal/logout/', views.admin_portal_logout, name='admin_portal_logout'),
    path('admin-portal/', views.admin_portal, name='admin_portal'),
    path('admin-portal/investors/add/', views.admin_portal_add_investor, name='admin_portal_add_investor'),
    path('admin-portal/investors/<int:pk>/delete/', views.admin_portal_delete_investor, name='admin_portal_delete_investor'),
    path('admin-portal/investors/<int:pk>/toggle/', views.admin_portal_toggle_investor, name='admin_portal_toggle_investor'),
    path('investor/login/', views.investor_login, name='investor_login'),
    path('investor/logout/', views.investor_logout, name='investor_logout'),
    path('investor/', views.investor_dashboard, name='investor_dashboard'),
    path('agent/login/', views.agent_login, name='agent_login'),
    path('agent/logout/', views.agent_logout, name='agent_logout'),
    path('agent/', views.agent_dashboard, name='agent_dashboard'),

    path('shopboy/marketplace-orders/', views.shopboy_marketplace_orders, name='shopboy_marketplace_orders'),
    path('marketplace/login/', views.marketplace_login, name='marketplace_login'),
    path('marketplace/register/', views.marketplace_signup, name='marketplace_signup'),
    path('marketplace/verify/', views.marketplace_verify, name='marketplace_verify'),
    path('marketplace/send-code/', views.marketplace_send_verification_code, name='marketplace_send_code'),
    path('marketplace/forgot-password/', views.marketplace_forgot_password, name='marketplace_forgot_password'),
    path('marketplace/forgot-password/send-code/', views.marketplace_forgot_password_send_code, name='marketplace_forgot_password_send_code'),
    path('marketplace/forgot-password/verify/', views.marketplace_forgot_password_verify_code, name='marketplace_forgot_password_verify_code'),
    path('marketplace/forgot-password/reset/', views.marketplace_forgot_password_reset, name='marketplace_forgot_password_reset'),
    path('marketplace/logout/', views.marketplace_logout, name='marketplace_logout'),
    path('marketplace/account/', views.marketplace_account, name='marketplace_account'),
    path('logout/', views.logout_view, name='logout'),
    path('add-to-cart/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('update-cart/<int:product_id>/', views.update_cart, name='update_cart'),
    path('remove-from-cart/<int:product_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('checkout/', views.checkout, name='checkout'),
    path('settings', views.settings, name='settings'),
    path('settings/update-profile/', views.update_profile, name='update_profile'),
    path('settings/add-shopboy/', views.add_shopboy, name='add_shopboy'),
    path('settings/toggle-shopboy/<int:pk>/', views.toggle_shopboy, name='toggle_shopboy'),
    path('settings/delete-shopboy/<int:pk>/', views.delete_shopboy, name='delete_shopboy'),
    path('settings/marketplace-assign/', views.update_marketplace_assignment, name='update_marketplace_assignment'),
    path('customer', views.customer, name='customer'),
    path('add-customer/', views.add_customer, name='add_customer'),
    path('edit-customer/<int:pk>/', views.edit_customer, name='edit_customer'),
    path('delete-customer/<int:pk>/', views.delete_customer, name='delete_customer'),
    path('reports', views.reports, name='reports'),
    path('expenses', views.expenses, name='expenses'),
    path('sales-history', views.sales_history, name='sales-history'),
    path('sales/<int:sale_id>/receipt/', views.sale_receipt, name='sale_receipt'),
    path('shopboy/sales/<int:sale_id>/receipt/', views.shopboy_sale_receipt, name='shopboy_sale_receipt'),
    path('inventory', views.inventory, name='inventory'),
    path('product/', views.product, name='product'),
    path('index/', views.index, name='index'),
    path('marketplace/', views.marketplace, name='marketplace'),
    path('marketplace/shop/<str:username>/', views.marketplace_shop, name='marketplace_shop'),
    path('marketplace/shop/<str:username>/order/', views.marketplace_place_order, name='marketplace_place_order'),
    path('marketplace/order/<uuid:public_id>/chat/', views.marketplace_order_chat, name='marketplace_order_chat'),
    path('marketplace/order/<uuid:public_id>/message/', views.marketplace_add_message, name='marketplace_add_message'),
    path('marketplace/order/<uuid:public_id>/status/', views.marketplace_update_status, name='marketplace_update_status'),
    path('feedback/', views.submit_feedback, name='submit_feedback'),
    path('home/', views.home, name='home'),
    path('', views.home, name='signup'),
    path('signup/', views.signup, name='signup'),
    path("signup/create-account/", views.signup_create_account, name="signup_create_account"),
    path("send-code/", views.send_code, name='send_code'),
    path("verify-code/", views.verify_code, name='verify-code'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
