# Generated by Django 6.0.2 on 2026-03-31 08:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('level', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('institution_type', models.CharField(choices=[('secondary', 'Secondary School'), ('tertiary', 'Tertiary Institution')], max_length=20)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('term', models.CharField(blank=True, max_length=50)),
                ('session', models.CharField(blank=True, max_length=20)),
                ('academic_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='edu.academicclass')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='edu.institution')),
            ],
        ),
        migrations.AddField(
            model_name='academicclass',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='edu.institution'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_type', models.CharField(choices=[('secondary', 'Secondary School'), ('tertiary', 'Tertiary Institution')], default='secondary', max_length=20)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('registry', 'Registry'), ('accountant', 'Accountant'), ('teacher', 'Teacher'), ('examiner', 'Examiner'), ('student', 'Student'), ('vc', 'VC'), ('ict-admin', 'ICT Admin'), ('hod', 'HOD'), ('lecturer', 'Lecturer')], default='student', max_length=20)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='edu.institution')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('staff_id', models.CharField(max_length=30, unique=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('registry', 'Registry'), ('accountant', 'Accountant'), ('teacher', 'Teacher'), ('examiner', 'Examiner'), ('student', 'Student'), ('vc', 'VC'), ('ict-admin', 'ICT Admin'), ('hod', 'HOD'), ('lecturer', 'Lecturer')], default='teacher', max_length=20)),
                ('department', models.CharField(blank=True, max_length=120)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='edu.institution')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('student_id', models.CharField(max_length=30, unique=True)),
                ('status', models.CharField(default='Active', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('academic_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='edu.academicclass')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='edu.institution')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(default='Paid', max_length=20)),
                ('paid_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='edu.institution')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='edu.student')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(blank=True, max_length=20)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='edu.institution')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test1', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('test2', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('assignment', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('exam', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('grade', models.CharField(blank=True, max_length=2)),
                ('term', models.CharField(blank=True, max_length=50)),
                ('session', models.CharField(blank=True, max_length=20)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='edu.institution')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.subject')),
            ],
        ),
    ]

