# Generated by Django 6.0.2 on 2026-03-31 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0006_institution_school_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='user_sequence',
            field=models.PositiveIntegerField(default=0),
        ),
    ]

