# Generated by Django 6.0.2 on 2026-04-01 08:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0009_staff_photo_student_next_of_kin_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('academic_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_subjects', to='edu.academicclass')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_classes', to='edu.subject')),
            ],
            options={
                'unique_together': {('academic_class', 'subject')},
            },
        ),
        migrations.AddField(
            model_name='academicclass',
            name='subjects',
            field=models.ManyToManyField(blank=True, through='edu.ClassSubject', to='edu.subject'),
        ),
    ]

