# Generated by Django 6.0.2 on 2026-04-01 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0010_classsubject_academicclass_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='applies_to_all',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fee',
            name='classes',
            field=models.ManyToManyField(blank=True, related_name='fees', to='edu.academicclass'),
        ),
        migrations.AddField(
            model_name='fee',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='fees', to='edu.department'),
        ),
        migrations.AddField(
            model_name='fee',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fee',
            name='fee_type',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]

