# Generated by Django 6.0.2 on 2026-05-08 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0013_teachersubjectassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='cac_certificate',
            field=models.FileField(blank=True, null=True, upload_to='institutions/verification/cac_certificates/'),
        ),
        migrations.AddField(
            model_name='institution',
            name='cac_status_report',
            field=models.FileField(blank=True, null=True, upload_to='institutions/verification/cac_status_reports/'),
        ),
        migrations.AddField(
            model_name='institution',
            name='ministry_approval',
            field=models.FileField(blank=True, null=True, upload_to='institutions/verification/ministry_approvals/'),
        ),
        migrations.AddField(
            model_name='institution',
            name='operating_license',
            field=models.FileField(blank=True, null=True, upload_to='institutions/verification/operating_licenses/'),
        ),
        migrations.AddField(
            model_name='institution',
            name='owner_valid_id',
            field=models.FileField(blank=True, null=True, upload_to='institutions/verification/owner_ids/'),
        ),
        migrations.AddField(
            model_name='institution',
            name='proof_of_address',
            field=models.FileField(blank=True, null=True, upload_to='institutions/verification/address_documents/'),
        ),
        migrations.AddField(
            model_name='institution',
            name='school_letterhead',
            field=models.FileField(blank=True, null=True, upload_to='institutions/verification/letterheads/'),
        ),
        migrations.AddField(
            model_name='institution',
            name='school_stamp',
            field=models.FileField(blank=True, null=True, upload_to='institutions/verification/stamps/'),
        ),
        migrations.AddField(
            model_name='institution',
            name='tin_certificate',
            field=models.FileField(blank=True, null=True, upload_to='institutions/verification/tax_documents/'),
        ),
        migrations.AddField(
            model_name='institution',
            name='utility_bill',
            field=models.FileField(blank=True, null=True, upload_to='institutions/verification/address_documents/'),
        ),
        migrations.AddField(
            model_name='institution',
            name='verification_review_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='institution',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
