# Generated by Django 6.0.2 on 2026-05-08 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0014_institution_cac_certificate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='fee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='edu.fee'),
        ),
    ]
