# Generated by Django 6.0.2 on 2026-05-08 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0016_payment_gateway_reference_payment_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicclass',
            name='academic_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='edu.academicsession'),
        ),
        migrations.AddField(
            model_name='academicclass',
            name='academic_term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='edu.academicterm'),
        ),
        migrations.AddField(
            model_name='result',
            name='academic_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='edu.academicclass'),
        ),
        migrations.AddField(
            model_name='result',
            name='academic_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='edu.academicsession'),
        ),
        migrations.AddField(
            model_name='result',
            name='academic_term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='edu.academicterm'),
        ),
        migrations.AddField(
            model_name='result',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='edu.staff'),
        ),
        migrations.AddField(
            model_name='resultsubmission',
            name='academic_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='result_submissions', to='edu.academicsession'),
        ),
        migrations.AddField(
            model_name='resultsubmission',
            name='academic_term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='result_submissions', to='edu.academicterm'),
        ),
    ]
