# Generated by Django 6.0.2 on 2026-05-08 19:00

from django.db import migrations, models


def normalize_result_statuses(apps, schema_editor):
    ResultSubmission = apps.get_model('edu', 'ResultSubmission')
    ResultSubmission.objects.filter(status='submitted').update(status='submitted_to_examiner')
    ResultSubmission.objects.filter(status='reviewed').update(status='approved_by_examiner')
    ResultSubmission.objects.filter(status='approved').update(status='published')


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0017_academicclass_academic_session_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultsubmission',
            name='admin_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resultsubmission',
            name='examiner_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resultsubmission',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resultsubmission',
            name='teacher_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='resultsubmission',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted_to_examiner', 'Submitted to Examiner'), ('returned_for_correction', 'Returned for Correction'), ('approved_by_examiner', 'Approved by Examiner'), ('approved_by_admin', 'Approved by Admin'), ('published', 'Published')], default='draft', max_length=30),
        ),
        migrations.RunPython(normalize_result_statuses, migrations.RunPython.noop),
    ]
