# Generated by Django 6.0.2 on 2026-05-08 19:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0018_resultsubmission_admin_comment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentClassHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_current', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('academic_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_history', to='edu.academicclass')),
                ('academic_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_class_history', to='edu.academicsession')),
                ('academic_term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_class_history', to='edu.academicterm')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_history', to='edu.student')),
            ],
            options={
                'unique_together': {('student', 'academic_class', 'academic_session', 'academic_term')},
            },
        ),
    ]
