# Generated by Django 6.0.2 on 2026-05-08 20:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0019_studentclasshistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='owner_id_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='institution',
            name='tin_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='InstitutionDocumentVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('cac_certificate', 'CAC Certificate'), ('cac_status_report', 'CAC Status Report'), ('ministry_approval', 'Ministry Approval'), ('operating_license', 'Operating License'), ('tin_certificate', 'TIN or Tax Certificate'), ('school_letterhead', 'School Letterhead'), ('school_stamp', 'School Stamp/Seal'), ('owner_valid_id', 'Owner/Admin Valid ID'), ('utility_bill', 'Utility Bill'), ('proof_of_address', 'Proof of Address')], max_length=40)),
                ('document_file', models.FileField(blank=True, null=True, upload_to='institutions/document_verifications/')),
                ('reference_value', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(choices=[('pending', 'Pending API Check'), ('api_verified', 'API Verified'), ('api_failed', 'API Failed'), ('manual_review', 'Manual Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('provider', models.CharField(blank=True, max_length=100)),
                ('api_checked_at', models.DateTimeField(blank=True, null=True)),
                ('api_response', models.JSONField(blank=True, default=dict)),
                ('review_note', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_verifications', to='edu.institution')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edu_document_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['institution__name', 'document_type'],
                'unique_together': {('institution', 'document_type')},
            },
        ),
    ]
