# Generated by Django 6.0.2 on 2026-05-15 20:00

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0020_institution_owner_id_number_institution_tin_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='registration_payment_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('25000.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='institution',
            name='registration_payment_paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='registration_payment_reference',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='institution',
            name='registration_payment_status',
            field=models.CharField(choices=[('pending', 'Pending Payment'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
