# Generated by Django 6.0.2 on 2026-05-15 20:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0021_institution_registration_payment_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(max_length=150)),
                ('bank_account_number', models.CharField(max_length=30)),
                ('bank_name', models.CharField(max_length=120)),
                ('bank_code', models.CharField(blank=True, max_length=30)),
                ('verified_account_name', models.CharField(max_length=150)),
                ('salary_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_date', models.DateField()),
                ('payment_frequency', models.CharField(choices=[('monthly', 'Monthly'), ('weekly', 'Weekly'), ('one_time', 'One-time')], default='monthly', max_length=20)),
                ('payment_gateway', models.CharField(choices=[('flutterwave', 'Flutterwave'), ('paystack', 'Paystack'), ('remita', 'Remita')], default='flutterwave', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('account_verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('failed', 'Failed'), ('manual_review', 'Manual Review')], default='pending', max_length=20)),
                ('account_verification_note', models.TextField(blank=True)),
                ('reference', models.CharField(blank=True, max_length=80, null=True, unique=True)),
                ('gateway_reference', models.CharField(blank=True, max_length=120)),
                ('failure_reason', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_salary_vouchers', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_salary_vouchers', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_vouchers', to='edu.institution')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_vouchers', to='edu.staff')),
            ],
            options={
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
    ]
