# Generated by Django 6.0.2 on 2026-05-16 09:22

from django.db import migrations, models


def trust_existing_profile_emails(apps, schema_editor):
    Profile = apps.get_model('edu', 'Profile')
    Profile.objects.filter(user__email__isnull=False).exclude(user__email='').update(email_verified=True)


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0022_salaryvoucher'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_verification_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='email_verification_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='email_verification_token',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='profile',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='password_reset_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='password_reset_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='password_reset_token',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.RunPython(trust_existing_profile_emails, migrations.RunPython.noop),
    ]
