# Generated by Codex on 2026-06-08

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0023_profile_email_verification_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='registration_payment_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('70000.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='institution',
            name='subscription_active_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='subscription_billing_cycle',
            field=models.CharField(choices=[('monthly', 'Monthly Plan'), ('termly', 'Termly Plan')], default='termly', max_length=20),
        ),
        migrations.AddField(
            model_name='institution',
            name='subscription_last_paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='subscription_last_payment_reference',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
