# Generated by Django 5.2.15 on 2026-08-12 01:37

from django.db import migrations, models


PACKAGE_LIMITS = {
    'starter': 50,
    'basic': 100,
    'growth': 200,
    'standard': 350,
    'premium': 500,
    'enterprise': 750,
    'enterprise-plus': 751,
}


def backfill_subscription_fields(apps, schema_editor):
    Institution = apps.get_model('edu', 'Institution')
    for institution in Institution.objects.all():
        institution.student_limit = PACKAGE_LIMITS.get(institution.subscription_package, 50)
        if institution.subscription_active_until and not institution.subscription_expiry_date:
            institution.subscription_expiry_date = institution.subscription_active_until
        if institution.registration_payment_paid_at and not institution.subscription_start_date:
            institution.subscription_start_date = institution.registration_payment_paid_at.date()
        if institution.registration_payment_status == 'paid':
            institution.subscription_status = 'active'
        else:
            institution.subscription_status = 'pending'
        institution.save(update_fields=[
            'student_limit',
            'subscription_expiry_date',
            'subscription_start_date',
            'subscription_status',
        ])


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0025_institution_subscription_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='student_limit',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AddField(
            model_name='institution',
            name='subscription_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='subscription_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='subscription_status',
            field=models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('expired', 'Expired'), ('pending', 'Pending')], default='pending', max_length=20),
        ),
        migrations.RunPython(backfill_subscription_fields, migrations.RunPython.noop),
    ]
