# Generated by Django 5.2.15 on 2026-08-12 07:39

from django.db import migrations, models
from django.utils import timezone


DEFAULT_TRIAL_STUDENT_LIMIT = 20


def backfill_trial_fields(apps, schema_editor):
    Institution = apps.get_model('edu', 'Institution')
    EduSubscriptionSettings = apps.get_model('edu', 'EduSubscriptionSettings')
    EduSubscriptionSettings.objects.update_or_create(
        pk=1,
        defaults={'trial_student_limit': DEFAULT_TRIAL_STUDENT_LIMIT},
    )

    today = timezone.localdate()
    for institution in Institution.objects.all():
        update_fields = []
        if not institution.trial_student_limit:
            institution.trial_student_limit = DEFAULT_TRIAL_STUDENT_LIMIT
            update_fields.append('trial_student_limit')

        trial_reference = institution.registration_payment_reference in {'2-day-trial', '3-day-free-trial'}
        if institution.subscription_status == 'trial' or trial_reference:
            if not institution.trial_start_date:
                paid_date = institution.registration_payment_paid_at.date() if institution.registration_payment_paid_at else None
                institution.trial_start_date = institution.subscription_start_date or paid_date or today
                update_fields.append('trial_start_date')
            if not institution.trial_end_date:
                institution.trial_end_date = institution.subscription_expiry_date or institution.subscription_active_until
                update_fields.append('trial_end_date')
            if institution.trial_end_date and not institution.subscription_expiry_date:
                institution.subscription_expiry_date = institution.trial_end_date
                update_fields.append('subscription_expiry_date')
            if institution.trial_end_date and institution.trial_end_date <= today:
                institution.subscription_status = 'trial_expired'
                update_fields.append('subscription_status')
            elif institution.subscription_status != 'trial':
                institution.subscription_status = 'trial'
                update_fields.append('subscription_status')
            if not institution.has_used_free_trial:
                institution.has_used_free_trial = True
                update_fields.append('has_used_free_trial')

        if update_fields:
            institution.save(update_fields=sorted(set(update_fields)))


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0026_institution_student_limit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EduSubscriptionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trial_student_limit', models.PositiveIntegerField(default=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Edu Subscription Settings',
                'verbose_name_plural': 'Edu Subscription Settings',
            },
        ),
        migrations.AddField(
            model_name='institution',
            name='has_used_free_trial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='institution',
            name='trial_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='trial_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='trial_student_limit',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='institution',
            name='subscription_status',
            field=models.CharField(choices=[('trial', 'Free Trial'), ('trial_expired', 'Trial Expired'), ('active', 'Active'), ('expired', 'Expired'), ('pending', 'Pending')], default='pending', max_length=20),
        ),
        migrations.RunPython(backfill_trial_fields, migrations.RunPython.noop),
    ]
