# Generated by Django 5.2.15 on 2026-08-12 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0027_edusubscriptionsettings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='school_code',
            field=models.CharField(blank=True, max_length=63, null=True, unique=True),
        ),
    ]
