# Generated by Django 5.2.15 on 2026-09-23 06:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0028_alter_institution_school_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EduMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('registry', 'Registry'), ('accountant', 'Accountant'), ('teacher', 'Teacher'), ('examiner', 'Examiner'), ('student', 'Student'), ('vc', 'VC'), ('provost', 'Provost'), ('ict-admin', 'ICT Admin'), ('faculty-admin', 'Faculty Admin'), ('department-admin', 'Department Admin'), ('hod', 'HOD'), ('lecturer', 'Lecturer')], default='student', max_length=20)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='edu.department')),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='edu.faculty')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='edu.institution')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edu_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'institution'), name='unique_edu_membership_per_user')],
            },
        ),
    ]
