# Generated by Django 5.2.15 on 2026-09-23 06:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0029_edumembership'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_test1', models.DecimalField(decimal_places=2, max_digits=5)),
                ('previous_test2', models.DecimalField(decimal_places=2, max_digits=5)),
                ('previous_assignment', models.DecimalField(decimal_places=2, max_digits=5)),
                ('previous_exam', models.DecimalField(decimal_places=2, max_digits=5)),
                ('previous_total', models.DecimalField(decimal_places=2, max_digits=5)),
                ('previous_grade', models.CharField(blank=True, max_length=2)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='result_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='edu.result')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
    ]
