# Generated by Django 5.2.15 on 2026-09-24 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0030_resultauditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edumembership',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('registry', 'Registry'), ('accountant', 'Accountant'), ('teacher', 'Teacher'), ('examiner', 'Examiner'), ('student', 'Student'), ('vc', 'VC'), ('provost', 'Provost'), ('ict-admin', 'ICT Admin'), ('faculty-admin', 'Faculty Admin'), ('department-admin', 'Department Admin'), ('hod', 'HOD'), ('lecturer', 'Lecturer'), ('parent', 'Parent')], default='student', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('registry', 'Registry'), ('accountant', 'Accountant'), ('teacher', 'Teacher'), ('examiner', 'Examiner'), ('student', 'Student'), ('vc', 'VC'), ('provost', 'Provost'), ('ict-admin', 'ICT Admin'), ('faculty-admin', 'Faculty Admin'), ('department-admin', 'Department Admin'), ('hod', 'HOD'), ('lecturer', 'Lecturer'), ('parent', 'Parent')], default='student', max_length=20),
        ),
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('registry', 'Registry'), ('accountant', 'Accountant'), ('teacher', 'Teacher'), ('examiner', 'Examiner'), ('student', 'Student'), ('vc', 'VC'), ('provost', 'Provost'), ('ict-admin', 'ICT Admin'), ('faculty-admin', 'Faculty Admin'), ('department-admin', 'Department Admin'), ('hod', 'HOD'), ('lecturer', 'Lecturer'), ('parent', 'Parent')], default='teacher', max_length=20),
        ),
        migrations.CreateModel(
            name='StudentGuardian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardian_links', to='edu.edumembership')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardians', to='edu.student')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('student', 'membership'), name='unique_guardian_link_per_student')],
            },
        ),
    ]
