from django.urls import path
from . import views

app_name = "edu"

urlpatterns = [
    path('', views.index, name='index'),
    path('secondary/login/', views.secondary_login, name='secondary_login'),
    path('secondary/register/', views.secondary_school_register, name='secondary_register'),
    path('secondary/admin/register/', views.secondary_admin_register, name='secondary_admin_register'),
    path('secondary/users/create/', views.secondary_create_user, name='secondary_create_user'),
    path('secondary/classes/add/', views.secondary_add_class, name='secondary_add_class'),
    path('secondary/sessions/add/', views.secondary_add_session_term, name='secondary_add_session_term'),
    path('secondary/classes/session-term/', views.secondary_assign_class_session_term, name='secondary_assign_class_session_term'),
    path('secondary/students/add/', views.secondary_add_student, name='secondary_add_student'),
    path('secondary/teachers/assign/', views.secondary_assign_teacher, name='secondary_assign_teacher'),
    path('secondary/teachers/assign-subject/', views.secondary_assign_teacher_subject, name='secondary_assign_teacher_subject'),
    path('secondary/subjects/add/', views.secondary_add_subject, name='secondary_add_subject'),
    path('secondary/teachers/add/', views.secondary_add_teacher, name='secondary_add_teacher'),
    path('secondary/classes/subjects/', views.secondary_assign_subjects, name='secondary_assign_subjects'),
    path('secondary/classes/subjects/remove/', views.secondary_remove_class_subject, name='secondary_remove_class_subject'),
    path('secondary/fees/create/', views.secondary_create_fee, name='secondary_create_fee'),
    path('secondary/fees/<int:fee_id>/delete/', views.secondary_delete_fee, name='secondary_delete_fee'),
    path('secondary/payments/record/', views.secondary_record_payment, name='secondary_record_payment'),
    path('secondary/payments/online/', views.secondary_online_payment, name='secondary_online_payment'),
    path('secondary/student/payments/online/', views.secondary_student_online_payment, name='secondary_student_online_payment'),
    path('secondary/payments/<str:reference>/receipt/', views.secondary_payment_receipt, name='secondary_payment_receipt'),
    path('secondary/payment/settings/', views.secondary_payment_settings, name='secondary_payment_settings'),
    path('secondary/teacher/scores/save/', views.secondary_save_scores, name='secondary_save_scores'),
    path('secondary/teacher/results/submit/', views.secondary_submit_results, name='secondary_submit_results'),
    path('secondary/examiner/results/review/', views.secondary_review_results, name='secondary_review_results'),
    path('secondary/admin/results/approve/', views.secondary_admin_result_approval, name='secondary_admin_result_approval'),
    path('secondary/student/profile/update/', views.secondary_student_profile_update, name='secondary_student_profile_update'),
    path('tertiary/login/', views.tertiary_login, name='tertiary_login'),
    path('tertiary/register/', views.tertiary_school_register, name='tertiary_register'),
    path('tertiary/users/create/', views.tertiary_create_user, name='tertiary_create_user'),
    path('tertiary/fees/create/', views.tertiary_create_fee, name='tertiary_create_fee'),
    path('tertiary/fees/<int:fee_id>/delete/', views.tertiary_delete_fee, name='tertiary_delete_fee'),
    path('tertiary/payment/settings/', views.tertiary_payment_settings, name='tertiary_payment_settings'),
    path('approve/<int:profile_id>/', views.approve_profile, name='approve_profile'),
    path('logout/', views.logout, name='logout'),
    path('secondary/<str:role>/', views.secondary_dashboard, name='secondary_dashboard'),
    path('secondary/<str:role>/<str:page>/', views.secondary_page, name='secondary_page'),
    path('tertiary/<str:role>/', views.tertiary_dashboard, name='tertiary_dashboard'),
    path('tertiary/<str:role>/<str:page>/', views.tertiary_page, name='tertiary_page'),
]
