from django.urls import path
from . import views

app_name = "edu"

protected = views.edu_portal_access_required

urlpatterns = [
    path('', views.index, name='index'),
    path('verify-email/<str:token>/', views.verify_email, name='verify_email'),
    path('forgot-password/', views.forgot_password, name='forgot_password'),
    path('reset-password/<str:token>/', views.reset_password, name='reset_password'),
    path('subscription/renew/', views.edu_subscription_renewal, name='subscription_renewal'),
    path('school-login/', views.school_portal_lookup, name='school_portal_lookup'),
    path('subdomain/check/', views.edu_subdomain_availability, name='subdomain_check'),
    path('portal/<str:school_code>/', views.school_portal_fallback, name='school_portal_fallback'),
    path('portal/<str:school_code>/dashboard/', views.school_portal_fallback_dashboard, name='school_portal_fallback_dashboard'),
    path('register/', views.secondary_school_register, name='register'),
    path('secondary/login/', views.secondary_login, name='secondary_login'),
    path('secondary/register/', views.secondary_school_register, name='secondary_register'),
    path('secondary/register/<str:school_code>/payment/', views.secondary_registration_payment, name='secondary_registration_payment'),
    path('secondary/admin/register/', protected(views.secondary_admin_register), name='secondary_admin_register'),
    path('secondary/users/create/', protected(views.secondary_create_user), name='secondary_create_user'),
    path('secondary/classes/add/', protected(views.secondary_add_class), name='secondary_add_class'),
    path('secondary/sessions/add/', protected(views.secondary_add_session_term), name='secondary_add_session_term'),
    path('secondary/classes/session-term/', protected(views.secondary_assign_class_session_term), name='secondary_assign_class_session_term'),
    path('secondary/students/add/', protected(views.secondary_add_student), name='secondary_add_student'),
    path('secondary/students/assign-class/', protected(views.secondary_assign_student_class), name='secondary_assign_student_class'),
    path('secondary/teachers/assign/', protected(views.secondary_assign_teacher), name='secondary_assign_teacher'),
    path('secondary/teachers/assign-subject/', protected(views.secondary_assign_teacher_subject), name='secondary_assign_teacher_subject'),
    path('secondary/subjects/add/', protected(views.secondary_add_subject), name='secondary_add_subject'),
    path('secondary/teachers/add/', protected(views.secondary_add_teacher), name='secondary_add_teacher'),
    path('secondary/classes/subjects/', protected(views.secondary_assign_subjects), name='secondary_assign_subjects'),
    path('secondary/classes/subjects/remove/', protected(views.secondary_remove_class_subject), name='secondary_remove_class_subject'),
    path('secondary/fees/create/', protected(views.secondary_create_fee), name='secondary_create_fee'),
    path('secondary/fees/<int:fee_id>/delete/', protected(views.secondary_delete_fee), name='secondary_delete_fee'),
    path('secondary/payments/record/', protected(views.secondary_record_payment), name='secondary_record_payment'),
    path('secondary/payments/online/', protected(views.secondary_online_payment), name='secondary_online_payment'),
    path('secondary/student/payments/online/', protected(views.secondary_student_online_payment), name='secondary_student_online_payment'),
    path('secondary/payments/<str:reference>/receipt/', protected(views.secondary_payment_receipt), name='secondary_payment_receipt'),
    path('secondary/payment/settings/', protected(views.secondary_payment_settings), name='secondary_payment_settings'),
    path('secondary/salary-vouchers/create/', protected(views.secondary_create_salary_voucher), name='secondary_create_salary_voucher'),
    path('secondary/salary-vouchers/<int:voucher_id>/approve/', protected(views.secondary_approve_salary_voucher), name='secondary_approve_salary_voucher'),
    path('secondary/salary-vouchers/process/', protected(views.secondary_process_salary_vouchers), name='secondary_process_salary_vouchers'),
    path('secondary/teacher/scores/save/', protected(views.secondary_save_scores), name='secondary_save_scores'),
    path('secondary/teacher/results/submit/', protected(views.secondary_submit_results), name='secondary_submit_results'),
    path('secondary/examiner/results/review/', protected(views.secondary_review_results), name='secondary_review_results'),
    path('secondary/admin/results/approve/', protected(views.secondary_admin_result_approval), name='secondary_admin_result_approval'),
    path('secondary/student/profile/update/', protected(views.secondary_student_profile_update), name='secondary_student_profile_update'),
    path('tertiary/login/', views.tertiary_login, name='tertiary_login'),
    path('tertiary/register/', views.tertiary_school_register, name='tertiary_register'),
    path('tertiary/register/<str:school_code>/payment/', views.tertiary_registration_payment, name='tertiary_registration_payment'),
    path('tertiary/users/create/', protected(views.tertiary_create_user), name='tertiary_create_user'),
    path('tertiary/fees/create/', protected(views.tertiary_create_fee), name='tertiary_create_fee'),
    path('tertiary/fees/<int:fee_id>/delete/', protected(views.tertiary_delete_fee), name='tertiary_delete_fee'),
    path('tertiary/payment/settings/', protected(views.tertiary_payment_settings), name='tertiary_payment_settings'),
    path('approve/<int:profile_id>/', protected(views.approve_profile), name='approve_profile'),
    path('logout/', views.logout, name='logout'),
    path('secondary/<str:role>/', protected(views.secondary_dashboard), name='secondary_dashboard'),
    path('secondary/<str:role>/<str:page>/', protected(views.secondary_page), name='secondary_page'),
    path('tertiary/<str:role>/', protected(views.tertiary_dashboard), name='tertiary_dashboard'),
    path('tertiary/<str:role>/<str:page>/', protected(views.tertiary_page), name='tertiary_page'),
]
